name: Debug Build on Ubuntu 18.04 

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - LICENSE

jobs:
  build-ubuntu-18_04:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install PostgreSQL
      run: sudo apt-get install cmake postgresql postgresql-server-dev-all
    - name: CMake configure
      run: cmake . -DCMAKE_BUILD_TYPE=Debug
    - name: Build extensions
      run: make
    - name: Install extensions
      run: sudo make install
    - name: Run CTest
      run: ctest --verbose --output-on-failure .
